/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.miniproject.railwaysystem;


import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sham
 * Background MainPageTrain.jpg
 * Background MainPageGradient.png
 */
public class StartPage extends javax.swing.JFrame{
    Connection conn;
    /**
     * Creates new form MainPage 
     * @throws java.lang.ClassNotFoundException
     */
    public void loadDriver() throws ClassNotFoundException
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
    }
    public void createConnection() throws SQLException
    {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/ORCL", "sham", "sham");
            System.out.println("Connected to Oracle");
    }

    /**
     *
     */
    public StartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        LoadingLabel = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Railway Resevation System");
        setIconImage(new javax.swing.ImageIcon("D:\\dbms\\RailwaySystem\\src\\main\\java\\com\\miniproject\\railwaysystem\\Assets\\TrainIcon.jpg").getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 102, 102));
        title.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 51, 102));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Railway Reservation System");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 450, 60));

        icon.setIcon(new javax.swing.ImageIcon("D:\\dbms\\RailwaySystem\\src\\main\\java\\com\\miniproject\\railwaysystem\\Assets\\MainPageTrain.jpg")); // NOI18N
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 640, 340));

        loadingBar.setBackground(new java.awt.Color(102, 255, 0));
        jPanel1.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 800, 20));

        LoadingLabel.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        LoadingLabel.setText("Loading...");
        jPanel1.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 403, 310, 20));

        LoadingValue.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        LoadingValue.setText("0 %");
        jPanel1.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 60, 20));

        bg.setIcon(new javax.swing.ImageIcon("D:\\dbms\\RailwaySystem\\src\\main\\java\\com\\miniproject\\railwaysystem\\Assets\\MainPageGradient.png")); // NOI18N
        bg.setText("RAILWAY RESERVATION SYSTEM");
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 830, 520));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void start()
    {
        try{
            for(int i=0;i<=100;i++){
                Thread.sleep(30);
                this.LoadingValue.setText(i+"%");
                if(i==10){
                    this.LoadingLabel.setText("Starting Application....");
                }
                if(i==30){
                    this.loadDriver();
                    this.LoadingLabel.setText("Loading Drivers.....");
                }
                if(i==50){
                    this.LoadingLabel.setText("Creating a connection......");
                }
                if(i==70){
                    this.createConnection();
                    this.LoadingLabel.setText("Connecting to Oracle......");
                }
                if(i==90){
                    this.LoadingLabel.setText("Connected to Oracle......");
                }
                this.loadingBar.setValue(i);
            }
            this.dispose();
            MainPage nf = new MainPage(conn);
            nf.setVisible(true);
        }
        catch(InterruptedException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        catch(SQLException e)
        {
            System.out.println("Couldnt Connect to Oracle");
            JOptionPane.showMessageDialog(this, e);
            System.exit(0);
        }
        catch(ClassNotFoundException e)
        {
            System.out.println("Couldnt Load the driver");
            JOptionPane.showMessageDialog(this, e);
            System.exit(0);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
